# Generated by Django 5.0.6 on 2024-07-07 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0035_alter_group_options_and_more"),
        ("authentik_providers_radius", "0002_radiusprovider_mfa_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="RadiusPropertyMapping",
            fields=[
                (
                    "propertymapping_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_core.propertymapping",
                    ),
                ),
                ("radius_reply_attribute", models.TextField(verbose_name="RADIUS Name")),
                ("attibute_friendly_name", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "verbose_name": "RADIUS Property Mapping",
                "verbose_name_plural": "RADIUS Property Mappings",
            },
            bases=("authentik_core.propertymapping",),
        ),
    ]
